version: "3"

services:
  pico-starlight-node:
    container_name: pico-starlight
    image: gruffalo1/pico-starlight-node:latest
    ports:
      - "3000:3000/tcp"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      TZ: Europe/London